### ISSUE TITLE
Frontmatter custom date field can't be parsed by Hugo

### ISSUE THREAD

**Issue by noorhammad** [ModiiMedia/contentful-hugo#8] opened 2019-10-29 05:36 UTC
Steps to recreate:

- Add field to Content Model of "Date and Time" type
- Set "Field id" to "date"
- Set field "Format" to "Date and time with timezone"
- Set field "Time mode" to "24 Hour"
- Edit Entry and set field value (date, time, timezone)

Hugo correctly updates frontmatter "date" value with Contentful field value however the date/time format is different from sys format (updated / createdAt).

Calling {{ .Params.date | dateFormat "2 Jan 2006" }} returns errors such as:

> Failed to render pages: render of "page" failed: "/PROJECT/blog/single.html:17:30": execute of template failed: template: blog/single.html:17:30: executing "main" at <dateFormat "2 Jan 2006">: error calling dateFormat: unable to cast <nil> of type <nil> to Time
github.com/gohugoio/hugo/hugolib.(*Site).renderPages

**Comment by joshmossas** [comment] 2019-10-29 20:26
Hey @noorhammad I've just merged a pull request that should resolve this issue. (See here: https://github.com/ModiiMedia/contentful-hugo/pull/9)

Could you update to the latest version and confirm if the issue is still happening? Thanks.

**Comment by noorhammad** [comment] 2019-10-29 23:55
@joshmossas certainly does, issue resolved. Thanks for updating.

**Closed** 2019-10-30 01:16 UTC
